name: Atualizacao Diaria IPMA

on:
  push:
    branches: [ main ]
  schedule:
    # O primeiro campo '15' define o minuto. 
    # O segundo '*' define que corre em todas as horas.
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissão necessária para o robô conseguir gravar os dados no GitHub
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Correr o robo
        run: python main.py
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}

      - name: Commit e Push dos Dados
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Atualização Automática: Dados IPMA (Minuto 15)"
          # Garante que guarda tanto o CSV como o XLSX
          file_pattern: 'Painel_Mestre_IPMA.*' 

      - name: Guardar os ficheiros como resultado (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: dados-ipma
          path: Painel_Mestre_IPMA.*
