name: Robô IPMA - 10 Minutos

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Aceder ao Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Preparar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar Bibliotecas
        run: pip install -r requirements.txt

      - name: Executar o Extrator IPMA
        run: python main.py

      - name: Forçar Atualização e Gravar Ficheiros
        run: |
          # 1. Configura quem é o "robô" que está a gravar
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 2. Adiciona os ficheiros gerados à lista
          git add Painel_Mestre_IPMA.csv Painel_Mestre_IPMA.xlsx
          
          # 3. Regista as alterações (apenas se houver diferenças)
          git commit -m "🤖 Atualização Automática: Dados IPMA" || echo "Sem alterações para gravar"
          
          # 4. Puxa as tuas alterações manuais e coloca as do robô por cima (resolve o erro)
          git pull --rebase origin main
          
          # 5. Envia finalmente tudo para o GitHub
          git push origin main
