name: Atualizacao Diaria IPMA
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Instalar Python
        uses: actions/setup-python@v5 # Atualizado para v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Correr o robo
        run: python main.py
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}

      - name: Guardar o ficheiro como resultado
        uses: actions/upload-artifact@v4 # Já estava em v4
        with:
          name: dados-ipma
          path: Painel_Mestre_IPMA.xlsx
